"""followers

Revision ID: 5930cacdc8b1
Revises: 8de8d77c7e9a
Create Date: 2019-07-18 10:41:40.523619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5930cacdc8b1'
down_revision = '8de8d77c7e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
